apiVersion: apps/v1
kind: Deployment
metadata:
  name: service2-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service2
  template:
    metadata:
      labels:
        app: service2
    spec:
      containers:
        - name: service2
          image: angpaoprw/service2
---
apiVersion: v1
kind: Service
metadata:
  name: service2-srv
spec:
  selector:
    app:  service2
  ports:
    - name: serice1
      protocol: TCP
      port: 5001
      targetPort: 5001