apiVersion: apps/v1
kind: Deployment
metadata:
  name: service1-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service1
  template:
    metadata:
      labels:
        app: service1
    spec:
      containers:
        - name: service1
          image: angpaoprw/service1
---
apiVersion: v1
kind: Service
metadata:
  name: service1-srv
spec:
  selector:
    app:  service1
  ports:
    - name: serice1
      protocol: TCP
      port: 5000
      targetPort: 5000