apiVersion: apps/v1
kind: Deployment
metadata:
  name: service1-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service1
  template:
    metadata:
      labels:
        app: service1
    spec:
      containers:
        - name: service1
          image: angpaoprw/service1
          env:
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              value: 'http://nats-srv:4222'
            - name: NATS_CLUSTER_ID
              value: test
            - name: MONGO_URL
              value: 'mongodb://service1-mongo-srv:27017/service1'
---
apiVersion: v1
kind: Service
metadata:
  name: service1-srv
spec:
  selector:
    app:  service1
  ports:
    - name: serice1
      protocol: TCP
      port: 5000
      targetPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: service1-nodeport-srv
spec:
  type: NodePort
  selector:
    app:  service1
  ports:
    - name: serice1
      protocol: TCP
      port: 5000
      targetPort: 5000